export default (
  '<div class="simplepicker" data-simplepicker-action="hide" touch-action="none" tabindex="-1" role="dialog">'
    + '<div class="simplepicker-dialog" role="document">'
      + '<div class="simplepicker-header">'
        + '<h4 class="simplepicker-title">{{ title }}</h4>'
        + '<button type="button" class="simplepicker-close" data-simplepicker-action="hide" aria-label="Close">&times;</button>'
      + '</div>'
      + '<div class="simplepicker-body">'
        + '<div class="simplepicker-grid"></div>'
      + '</div>'
      + '<div class="simplepicker-footer">'
        + '<button type="button" class="simplepicker-cancel" data-simplepicker-action="hide">{{ cancel }}</button>'
        + '<button type="button" class="simplepicker-confirm" data-simplepicker-action="pick">{{ confirm }}</button>'
      + '</div>'
    + '</div>'
  + '</div>'
);
